recipebook/ledger/urls.py
from django.urls import path
from .views import recipe_list, recipe_ingredients

urlpatterns = [
   path('recipes/list/', recipe_list, name='recipe_list'),
   path('recipe/<int:recipe_id>/', recipe_ingredients, name='recipe_ingredients')
]


app_name = 'ledger'

recipebook/recipebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("ledger.urls")),
]

recipebook/ledger/models.py
from django.db import models
from django.urls import reverse

class Ingredient(models.Model):
  name = models.CharField(max_length=200)

  def __str__(self):
    return self.name
  
  def get_absolute_url(self):
    return reverse("ledger:ingredients", args=[str(self.id)])

class Recipe(models.Model):
  name = models.CharField(max_length=200)

  def __str__(self):
    return self.name
  
  def get_absolute_url(self):
    return reverse("ledger:recipe_ingredients", args=[str(self.id)])

class RecipeIngredient(models.Model):
  quantity = models.CharField(max_length=200)
  ingredient = models.ForeignKey(
    Ingredient,
    on_delete=models.CASCADE
  )
  recipe = models.ForeignKey(
    Recipe,
    on_delete=models.CASCADE
  )

recipebook/ledger/views.py
from django.shortcuts import render
from .models import Recipe, RecipeIngredient

def recipe_list(request):
    recipes = Recipe.objects.all()
    return render(request, 'recipe_list.html', {"recipes": recipes})

def recipe_ingredients(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    return render(request, 'recipe_ingredients.html', {"recipe": recipe})

recipebook/ledger/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
 <title>{%block title%}Recipe Book{%endblock%}</title>
</head>
<body>
 <h1>Recipe Book</h1>
 <div id='content'>
   {% block content%}{%endblock%}
 </div>
</body>
</html>

recipebook/ledger/templates/recipe_ingredients.html
{% extends 'base.html'%}
{% load static%}
{%block title%}Recipe Book{%endblock%}
{% block content%}
  <h2>Recipe {{ recipe.id }}</h2>
  <h3>Ingredients:</h3>
  {% for recipe_ingredient in recipe.recipeingredient_set.all %}
    <li>{{ recipe_ingredient.ingredient.name }} | {{ recipe_ingredient.quantity }}</li>
  {% endfor %}
{%endblock%}

recipebook/ledger/templates/recipe_list.html
{% extends 'base.html'%}
{% load static%}
{%block title%}Recipe Book{%endblock%}
{% block content%}
 <ul>
   {% for recipe in recipes%}
      <li><a href="{{ recipe.get_absolute_url }}">{{ recipe.name }}</a></li>
   {%endfor%}
 </ul>
{%endblock%}